#!/bin/sh

if [ "$1" = "" -o "$2" = "" -o "$3" = "" ]; then
    echo "O comando deve ser chamado da seguinte forma:"
    echo "test-solution [Pasta com as questões] [Inicial da questão a ser resolvida] [Arquivo com o código de solução]"
    exit 1
fi

problem_folder="$1/$2"
numero_de_testes=$(ls -1 "$problem_folder/input/" | wc -l)

i=1
halign=

if [ $numero_de_testes -ge 100 ]; then
	halign=3
elif [ $numero_de_testes -ge 10 ]; then
	halign=2
else
	halign=1
fi

g++ "$3" &&
echo "Questão $2" &&
for f in $(ls -1 "$problem_folder/input/"); do
    printf "T%-${halign}d: " "$i"
    i=$[ $i + 1 ]
    ./a.out < "$problem_folder/input/$f" > tmp
    if cmp -s tmp "$problem_folder/output/$f"; then
        echo "Sucesso!"
    else
        echo "Resposta incorreta X"
    fi
done &&
rm a.out tmp
